site_name: "BICAN Knowledge Graph Models Documentation"
site_url: https://brain-bican.github.io/models/
theme:
  name: material
  palette:
    scheme: default
    primary: white
  logo: images/bican_logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
  - panzoom:
      full_screen: true
      always_show_hint: true
      hint_location: "top"


nav:
  - Overview: index.md
  - Models:
    - Library Generation: index_library_generation.md
    - Anatomical Structure: index_anatomical_structure.md
    - Genome Annotation: index_genome_annotation.md
    - Assertion Evidence: index_assertion_evidence.md
    - BKE Taxonomy: index_bke_taxonomy.md
  - Visualizations: 
    - Library Generation: library_generation.md
    - Anatomical Structure: anatomical_structure.md
    - Genome Annotation: genome_annotation.md
    - Assertion Evidence: assertion_evidence.md
    - BKE Taxonomy: bke_taxonomy.md
repo_url: https://github.com/brain-bican/models

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format